; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Brandy Mol
AppVerName=Brandy Mol 1.0
AppPublisher=BrandyMol
DefaultDirName=C:\BrandyMol
DefaultGroupName=Brandy Mol
LicenseFile=C:\VTKBANBRANDY\ToInstall\Licencia.txt
InfoBeforeFile=C:\VTKBANBRANDY\ToInstall\PreInformacion.txt
InfoAfterFile=
OutputDir=C:\VTKBANBRANDY\installs\install netfull
OutputBaseFilename=BrandyMolSetupPRU
Compression=lzma
SolidCompression=true
AppVersion=1.0
UninstallDisplayName=Brandy Mol 1.0
ShowLanguageDialog=auto
WindowVisible=false
WizardImageFile=compiler:wizmodernimage-IS.bmp
WizardSmallImageFile=compiler:wizmodernsmallimage-IS.bmp
InternalCompressLevel=normal
DisableDirPage=true
AppCopyright=Gregorio Torres, Francisco Nájera y Oscar Noel Amaya
ChangesEnvironment=true

[Languages]
Name: spanish; MessagesFile: compiler:Languages\Spanish.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\..\ToInstall\bin\brandy.ico; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\colors.ini; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Colors.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\conf.ini; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Conf.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Data.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Fich.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\GUI.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Icon.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\inchi.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\launcher.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Log.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\logo.JPG; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\main.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Mopac.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\mopacesp.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\PLOBRAN.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tcl84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tclpip84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Tinker.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tk84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tlistadll.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\VisorVTK.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\wish84.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\acercaDe.jpg; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\scanocvm.exe; DestDir: {app}\bin\
Source: ..\..\bin\Sc172.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\chm\amber98.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber98.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber99.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber99.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amoebapro.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amoebapro.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\carga.htm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\charmm27.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\charmm27.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\MM3BrandyMol.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\MM3BrandyMol.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\mm3pro.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\mm3pro.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\OPLSaa.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\oplsaa.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\vibration.htm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\brandymol.chm; DestDir: {app}\chm\
;Source: ..\..\ToInstall\draw25.exe; DestDir: {tmp}
;Source: ..\..\ToInstall\MDLChime26SP4.exe; DestDir: {tmp}
;Source: ..\..\ToInstall\AN2000.exe; DestDir: {tmp}
;Source: ..\..\ToInstall\help25.exe; DestDir: {tmp}
Source: ..\..\ToInstall\unzip.bat; DestDir: {tmp}
Source: ..\..\ToInstall\tinker.bat; DestDir: {tmp}
Source: ..\..\ToInstall\7za.exe; DestDir: {tmp}
Source: ..\..\ToInstall\lib\bwidget1.7\images\bold.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\copy.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\cut.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\dragfile.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\dragicon.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\error.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\file.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\folder.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\hourglass.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\info.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\italic.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\minus.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\new.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\opcopy.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\open.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\openfold.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\oplink.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\opmove.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\overstrike.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\palette.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\passwd.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\paste.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\plus.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\print.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\question.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\redo.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\save.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\target.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\Thumbs.db; DestDir: {app}\lib\bwidget1.7\images; Attribs: hidden system
Source: ..\..\ToInstall\lib\bwidget1.7\images\underline.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\undo.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\warning.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\lang\da.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\de.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\en.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\es.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\fr.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\arrow.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\bitmap.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\button.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\buttonbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\color.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\combobox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dialog.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dragsite.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dropsite.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dynhelp.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\entry.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\font.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\init.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\label.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\labelentry.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\labelframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\listbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\mainframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\messagedlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\notebook.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\pagesmgr.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\panedw.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\panelframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\passwddlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\pkgIndex.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\progressbar.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\progressdlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollview.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollw.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\separator.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\spinbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\statusbar.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\titleframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\tree.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\utils.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\widget.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\xpm2image.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\Img1.3\jpegtcl10.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\pkgIndex.tcl; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\pngtcl126.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tifftcl361.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimg13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgbmp13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimggif13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgico13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgjpeg13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpcx13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpixmap13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpng13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgppm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgps13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgsgi13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgsun13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgtga13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgtiff13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgwindow13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgxbm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgxpm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\zlibtcl123.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\optcl\optcl.dll; DestDir: {app}\lib\optcl
Source: ..\..\ToInstall\lib\optcl\pkgIndex.tcl; DestDir: {app}\lib\optcl
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\registry.tap; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\tclreg11.dll; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\auto.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\history.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\init.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\ldAout.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\package.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\parray.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\safe.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclConfig-shared.sh; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclConfig.sh; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclIndex; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\word.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcllib1.8\math\bessel.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bigfloat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bigfloat2.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bignum.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\calculus.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\classic_polyns.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\combinatorics.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\constants.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\elliptic.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\exponential.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\fourier.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\fuzzy.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\geometry.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\interpolate.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\linalg.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\liststat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\math.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\misc.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\optimize.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\pdf_stat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\plotstat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\polynomials.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\qcomplex.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\rational_funcs.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\romannumerals.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\special.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\statistics.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\tclIndex; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8
Source: ..\..\ToInstall\lib\tk8.4\bgerror.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\button.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\choosedir.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\clrpick.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\comdlg.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\console.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\dialog.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\entry.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\focus.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\listbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\menu.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\mkpsenc.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\msgbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\obsolete.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\optMenu.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\palette.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\panedwindow.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\pkgIndex.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\prolog.ps; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\safetk.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\scale.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\scrlbar.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\spinbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tclIndex; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tearoff.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\text.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tk.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkAppInit.c; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkConfig-shared.sh; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkConfig.sh; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkfbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\unsupported.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\xmfbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\twapi\clipboard.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\com.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\console.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\desktop.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\disk.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\eventlog.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\LICENSE; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\network.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\nls.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\osinfo.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\pdh.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\pkgIndex.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\printer.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\process.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\security.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\services.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\share.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\shell.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\synch.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapi.dll; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapi.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapicallback.dll; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\ui.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\vtk\vtkcommon\vtkcommon.tcl; DestDir: {app}\lib\vtk\vtkcommon
Source: ..\..\ToInstall\lib\vtk\vtkfiltering\vtkfiltering.tcl; DestDir: {app}\lib\vtk\vtkfiltering
Source: ..\..\ToInstall\lib\vtk\vtkgraphics\vtkgraphics.tcl; DestDir: {app}\lib\vtk\vtkgraphics
Source: ..\..\ToInstall\lib\vtk\vtkhybrid\vtkhybrid.tcl; DestDir: {app}\lib\vtk\vtkhybrid
Source: ..\..\ToInstall\lib\vtk\vtkimaging\vtkimaging.tcl; DestDir: {app}\lib\vtk\vtkimaging
Source: ..\..\ToInstall\lib\vtk\vtkio\vtkio.tcl; DestDir: {app}\lib\vtk\vtkio
Source: ..\..\ToInstall\lib\vtk\vtkrendering\vtkrendering.tcl; DestDir: {app}\lib\vtk\vtkrendering
Source: ..\..\ToInstall\lib\vtk\vtkvolumerendering\vtkvolumerendering.tcl; DestDir: {app}\lib\vtk\vtkvolumerendering
Source: ..\..\ToInstall\lib\vtk\vtkwidgets\vtkwidgets.tcl; DestDir: {app}\lib\vtk\vtkwidgets
Source: ..\..\ToInstall\lib\vtk\bindings-iw.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\bindings-rw.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\bindings.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\Interactor.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\pkgIndex.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\setget.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtk.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkbase.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkCommon.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkCommonTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkDICOMParser.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkexoIIc.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkexpat.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkFiltering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkFilteringTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkfreetype.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkftgl.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGenericFiltering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGenericFilteringTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGraphics.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGraphicsTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkHybrid.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkHybridTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkImaging.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkImagingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkinteraction.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkIO.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkIOTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkjpeg.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkMPEG2Encode.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkNetCDF.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkParallel.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkParallelTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkpng.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkRendering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkRenderingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtksys.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtktesting.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtktiff.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkVolumeRendering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkVolumeRenderingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkWidgets.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkWidgetsTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkzlib.dll; DestDir: {app}\lib\vtk

[Icons]
Name: {group}\Brandy Mol; Filename: {app}\bin\launcher.exe; IconIndex: 0; Tasks: ; Languages: ; WorkingDir: {app}\bin; IconFilename: {app}\bin\brandy.ico
Name: {group}\{cm:UninstallProgram,Brandy Mol}; Filename: {uninstallexe}; Tasks: ; Languages: 
Name: {commondesktop}\Brandy Mol; Filename: {app}\bin\launcher.exe; Tasks: desktopicon; IconIndex: 0; WorkingDir: {app}\bin; IconFilename: {app}\bin\brandy.ico
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\Brandy Mol; Filename: {app}\bin\launcher.exe; Tasks: quicklaunchicon; IconIndex: 0; WorkingDir: {app}\bin; Languages: ; IconFilename: {app}\bin\brandy.ico

[Run]
Filename: {tmp}\unzip.bat; WorkingDir: {tmp}; Parameters: {app}\bin; Description: unzip; Flags: shellexec runhidden
Filename: {tmp}\tinker.bat; Parameters: {app}; WorkingDir: {tmp}; Flags: shellexec runhidden
Filename: {tmp}\draw25.exe; Description: Instalar MDL Isis Draw 2.5; Flags: postinstall skipifdoesntexist; StatusMsg: Instalando MDL Isis Draw 2.5  ........
Filename: {tmp}\MDLChime26SP4.exe; Description: Instalar MDL Chime; Flags: postinstall skipifdoesntexist; StatusMsg: Instalando MDL Chime ........
Filename: {tmp}\help25.exe; Description: Instalar Ayudas de Isis Draw; Flags: postinstall skipifdoesntexist; StatusMsg: Instalando Ayuda de Isis Draw 2.5  ........
Filename: {tmp}\AN2000.exe; Description: Instalar Modulo de Nomenclatura para Isis Draw; Flags: postinstall skipifdoesntexist; StatusMsg: Instalando Modulo de Nomenclatura para Isis Draw ........
Filename: {app}\bin\launcher.exe; Description: {cm:LaunchProgram,Brandy Mol}; Flags: nowait postinstall skipifsilent unchecked; WorkingDir: {app}\bin





[Dirs]
Name: {app}\bin
Name: {app}\chm
Name: {app}\lib

[INI]
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_PPAL>; String: {app}\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_CHM>; String: {app}\chm\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_TEMP>; String: {app}\temp\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_BIN>; String: {app}\bin\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_DATA>; String: {app}\data\
Filename: {app}\bin\conf.ini; Section: Preferencias; Key: <escala>; String: 9.1
Filename: {app}\bin\conf.ini; Section: Preferencias; Key: <CONSOLE>; String: hide

[Registry]
Root: HKLM; Subkey: SOFTWARE\Brandy Mol; ValueType: string; ValueName: Path; ValueData: {app}; Tasks: ; Languages: 
[LangOptions]
LanguageName=English
LanguageID=$0409

[_ISToolDownload]
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/analyze.zip; DestDir: {tmp}; DestName: analyze.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/minimize.zip; DestDir: {tmp}; DestName: minimize.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/newton.zip; DestDir: {tmp}; DestName: newton.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/optimize.zip; DestDir: {tmp}; DestName: optimize.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/path.zip; DestDir: {tmp}; DestName: path.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/saddle.zip; DestDir: {tmp}; DestName: saddle.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/scan.zip; DestDir: {tmp}; DestName: scan.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/spacefill.zip; DestDir: {tmp}; DestName: spacefill.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/superpose.zip; DestDir: {tmp}; DestName: superpose.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/vibrate.zip; DestDir: {tmp}; DestName: vibrate.zip
Source: http://150.214.238.162/svn/MOLMOD/SetupCompleto/Auxiliares/IsisDraw/draw25.exe; DestDir: {tmp}; DestName: draw25.exe
Source: http://150.214.238.162/svn/MOLMOD/SetupCompleto/Auxiliares/IsisDraw/help25.exe; DestDir: {tmp}; DestName: help25.exe
Source: http://150.214.238.162/svn/MOLMOD/SetupCompleto/Auxiliares/IsisDraw/AN2000.exe; DestDir: {tmp}; DestName: AN2000.exe
Source: http://gretor.cie.uma.es/svn/MOLMOD/SetupCompleto/Auxiliares/ChimeSP4/MDLChime26SP4.exe; DestDir: {tmp}; DestName: MDLChime26SP4.exe
[Code]
// Function generated by ISTool.

function NextButtonClick(CurPage: Integer): Boolean;
begin
	Result := istool_download(CurPage);
end;
procedure CreateTheWizardPages;
var
  Page: TWizardPage;
  Button, FormButton: TButton;
  CheckBox: TCheckBox;
  Edit: TEdit;
  PasswordEdit: TPasswordEdit;
  Memo: TMemo;
  Lbl, ProgressBarLabel: TLabel;
  ComboBox: TComboBox;
  ListBox: TListBox;
  StaticText: TNewStaticText;
  ProgressBar: TNewProgressBar;
  CheckListBox, CheckListBox2: TNewCheckListBox;
  FolderTreeView: TFolderTreeView;
  BitmapImage, BitmapImage2, BitmapImage3: TBitmapImage;
  BitmapFileName: String;
  RichEditViewer: TRichEditViewer;
begin
  { TNewCheckListBox }

  Page := CreateCustomPage(Page.ID, 'Custom wizard page controls', 'TNewCheckListBox');

  CheckListBox := TNewCheckListBox.Create(Page);
  CheckListBox.Width := Page.SurfaceWidth;
  CheckListBox.Height := ScaleY(97);
  CheckListBox.Flat := True;
  CheckListBox.Parent := Page.Surface;
  CheckListBox.AddCheckBox('TNewCheckListBox', '', 0, True, True, False, True, nil);
  CheckListBox.AddRadioButton('TNewCheckListBox', '', 1, True, True, nil);
  CheckListBox.AddRadioButton('TNewCheckListBox', '', 1, False, True, nil);
  CheckListBox.AddCheckBox('TNewCheckListBox', '', 0, True, True, False, True, nil);

  CheckListBox2 := TNewCheckListBox.Create(Page);
  CheckListBox2.Top := CheckListBox.Top + CheckListBox.Height + ScaleY(8);
  CheckListBox2.Width := Page.SurfaceWidth;
  CheckListBox2.Height := ScaleY(97);
  CheckListBox2.BorderStyle := bsNone;
  CheckListBox2.ParentColor := True;
  CheckListBox2.MinItemHeight := WizardForm.TasksList.MinItemHeight;
  CheckListBox2.ShowLines := False;
  CheckListBox2.WantTabs := True;
  CheckListBox2.Parent := Page.Surface;
  CheckListBox2.AddGroup('TNewCheckListBox', '', 0, nil);
  CheckListBox2.AddRadioButton('TNewCheckListBox', '', 0, True, True, nil);
  CheckListBox2.AddRadioButton('TNewCheckListBox', '', 0, False, True, nil);
  end;
  procedure InitializeWizard();
var
  AboutButton, CancelButton: TButton;
  URLLabel: TNewStaticText;
  BackgroundBitmapImage: TBitmapImage;
  BackgroundBitmapText: TNewStaticText;
begin
  { Custom wizard pages }

  CreateTheWizardPages;

end;
