; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Brandy Mol Net Full Install
AppVerName=Brandy Mol 1.0
AppPublisher=Banshee Inc.
DefaultDirName=C:\BrandyMol
DefaultGroupName=BrandyMol
LicenseFile=C:\VTKBANBRANDY\ToInstall\Licencia.txt
InfoBeforeFile=C:\VTKBANBRANDY\ToInstall\PreInformacion.txt
InfoAfterFile=C:\VTKBANBRANDY\ToInstall\PostInformacion.txt
OutputDir=C:\VTKBANBRANDY\installs\install netfull
OutputBaseFilename=BrandyMolNetFullSetup
Compression=lzma/ultra
SolidCompression=true
AppVersion=1.0
UninstallDisplayName=Brandy Mol 1.0
ShowLanguageDialog=auto
WindowVisible=false
WizardImageFile=compiler:wizmodernimage-IS.bmp
WizardSmallImageFile=compiler:wizmodernsmallimage-IS.bmp
InternalCompressLevel=normal

[Languages]
Name: spanish; MessagesFile: compiler:Languages\Spanish.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\..\ToInstall\bin\brandy.ico; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\colors.ini; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Colors.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\conf.ini; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Conf.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Data.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Fich.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\GUI.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Icon.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\inchi.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\launcher.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Log.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\logo.JPG; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\main.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Mopac.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\mopacesp.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\PLOBRAN.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tcl84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tclpip84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\Tinker.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tk84.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\tlistadll.dll; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\VisorVTK.tcl; DestDir: {app}\bin\
Source: ..\..\ToInstall\bin\wish84.exe; DestDir: {app}\bin\
Source: ..\..\ToInstall\chm\amber98.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber98.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber99.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amber99.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amoebapro.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\amoebapro.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\carga.htm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\charmm27.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\charmm27.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\MM3BrandyMol.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\MM3BrandyMol.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\mm3pro.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\mm3pro.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\OPLSaa.bdy; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\oplsaa.prm; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\TINKER.key; DestDir: {app}\chm\
Source: ..\..\ToInstall\chm\vibration.htm; DestDir: {app}\chm\
Source: ..\..\ToInstall\bin\acercaDe.jpg; DestDir: {app}\bin
Source: ..\..\ToInstall\bin\scanocvm.exe; DestDir: {app}\bin
Source: ..\..\ToInstall\draw25.exe; DestDir: {tmp}
Source: ..\..\ToInstall\MDLChime26SP4.exe; DestDir: {tmp}
Source: ..\..\ToInstall\AN2000.exe; DestDir: {tmp}
Source: ..\..\ToInstall\help25.exe; DestDir: {tmp}
Source: ..\..\ToInstall\unzip.bat; DestDir: {tmp}
Source: ..\..\ToInstall\7za.exe; DestDir: {tmp}
Source: ..\..\ToInstall\lib\bwidget1.7\images\bold.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\copy.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\cut.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\dragfile.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\dragicon.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\error.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\file.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\folder.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\hourglass.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\info.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\italic.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\minus.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\new.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\opcopy.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\open.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\openfold.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\oplink.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\opmove.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\overstrike.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\palette.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\passwd.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\paste.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\plus.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\print.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\question.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\redo.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\save.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\target.xbm; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\Thumbs.db; DestDir: {app}\lib\bwidget1.7\images; Attribs: hidden system
Source: ..\..\ToInstall\lib\bwidget1.7\images\underline.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\undo.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\images\warning.gif; DestDir: {app}\lib\bwidget1.7\images
Source: ..\..\ToInstall\lib\bwidget1.7\lang\da.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\de.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\en.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\es.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\lang\fr.rc; DestDir: {app}\lib\bwidget1.7\lang
Source: ..\..\ToInstall\lib\bwidget1.7\arrow.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\bitmap.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\button.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\buttonbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\bwidget.tap; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\color.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\combobox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dialog.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dragsite.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dropsite.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\dynhelp.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\entry.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\font.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\init.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\label.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\labelentry.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\labelframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\listbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\mainframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\messagedlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\notebook.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\pagesmgr.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\panedw.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\panelframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\passwddlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\pkgIndex.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\progressbar.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\progressdlg.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollview.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\scrollw.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\separator.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\spinbox.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\statusbar.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\titleframe.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\tree.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\utils.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\widget.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\bwidget1.7\xpm2image.tcl; DestDir: {app}\lib\bwidget1.7
Source: ..\..\ToInstall\lib\Img1.3\img.tap; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\jpegtcl10.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\pkgIndex.tcl; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\pngtcl126.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tifftcl361.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimg13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgbmp13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimggif13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgico13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgjpeg13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpcx13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpixmap13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgpng13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgppm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgps13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgsgi13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgsun13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgtga13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgtiff13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgwindow13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgxbm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\tkimgxpm13.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\Img1.3\zlibtcl123.dll; DestDir: {app}\lib\Img1.3
Source: ..\..\ToInstall\lib\optcl\optcl.dll; DestDir: {app}\lib\optcl
Source: ..\..\ToInstall\lib\optcl\optcl.tap; DestDir: {app}\lib\optcl
Source: ..\..\ToInstall\lib\optcl\pkgIndex.tcl; DestDir: {app}\lib\optcl
Source: ..\..\ToInstall\lib\tcl8.4\dde1.2\dde.tap; DestDir: {app}\lib\tcl8.4\dde1.2
Source: ..\..\ToInstall\lib\tcl8.4\dde1.2\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\dde1.2
Source: ..\..\ToInstall\lib\tcl8.4\dde1.2\tcldde12.dll; DestDir: {app}\lib\tcl8.4\dde1.2
Source: ..\..\ToInstall\lib\tcl8.4\encoding\ascii.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\big5.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1250.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1251.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1252.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1253.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1254.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1255.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1256.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1257.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp1258.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp437.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp737.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp775.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp850.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp852.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp855.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp857.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp860.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp861.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp862.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp863.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp864.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp865.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp866.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp869.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp874.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp932.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp936.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp949.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\cp950.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\dingbats.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\ebcdic.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\euc-cn.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\euc-jp.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\euc-kr.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\gb12345.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\gb1988.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\gb2312-raw.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\gb2312.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso2022-jp.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso2022-kr.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso2022.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-1.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-10.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-13.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-14.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-15.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-16.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-2.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-3.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-4.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-5.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-6.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-7.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-8.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\iso8859-9.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\jis0201.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\jis0208.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\jis0212.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\koi8-r.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\koi8-u.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\ksc5601.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macCentEuro.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macCroatian.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macCyrillic.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macDingbats.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macGreek.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macIceland.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macJapan.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macRoman.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macRomania.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macThai.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macTurkish.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\macUkraine.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\shiftjis.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\symbol.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\encoding\tis-620.enc; DestDir: {app}\lib\tcl8.4\encoding
Source: ..\..\ToInstall\lib\tcl8.4\http1.0\http.tcl; DestDir: {app}\lib\tcl8.4\http1.0
Source: ..\..\ToInstall\lib\tcl8.4\http1.0\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\http1.0
Source: ..\..\ToInstall\lib\tcl8.4\http2.5\http.tcl; DestDir: {app}\lib\tcl8.4\http2.5
Source: ..\..\ToInstall\lib\tcl8.4\http2.5\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\http2.5
Source: ..\..\ToInstall\lib\tcl8.4\msgcat1.3\msgcat.tcl; DestDir: {app}\lib\tcl8.4\msgcat1.3
Source: ..\..\ToInstall\lib\tcl8.4\msgcat1.3\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\msgcat1.3
Source: ..\..\ToInstall\lib\tcl8.4\opt0.4\optparse.tcl; DestDir: {app}\lib\tcl8.4\opt0.4
Source: ..\..\ToInstall\lib\tcl8.4\opt0.4\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\opt0.4
Source: ..\..\ToInstall\lib\tcl8.4\platform\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\platform
Source: ..\..\ToInstall\lib\tcl8.4\platform\platform.tcl; DestDir: {app}\lib\tcl8.4\platform
Source: ..\..\ToInstall\lib\tcl8.4\platform\shell.tcl; DestDir: {app}\lib\tcl8.4\platform
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\registry.tap; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\reg1.1\tclreg11.dll; DestDir: {app}\lib\tcl8.4\reg1.1
Source: ..\..\ToInstall\lib\tcl8.4\tbcload1.4\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\tbcload1.4
Source: ..\..\ToInstall\lib\tcl8.4\tbcload1.4\tbcload.tap; DestDir: {app}\lib\tcl8.4\tbcload1.4
Source: ..\..\ToInstall\lib\tcl8.4\tbcload1.4\tbcload14.dll; DestDir: {app}\lib\tcl8.4\tbcload1.4
Source: ..\..\ToInstall\lib\tcl8.4\tcltest2.2\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\tcltest2.2
Source: ..\..\ToInstall\lib\tcl8.4\tcltest2.2\tcltest.tcl; DestDir: {app}\lib\tcl8.4\tcltest2.2
Source: ..\..\ToInstall\lib\tcl8.4\thread2.6.3\pkgIndex.tcl; DestDir: {app}\lib\tcl8.4\thread2.6.3
Source: ..\..\ToInstall\lib\tcl8.4\thread2.6.3\thread263.dll; DestDir: {app}\lib\tcl8.4\thread2.6.3
Source: ..\..\ToInstall\lib\tcl8.4\thread2.6.3\ttrace.tcl; DestDir: {app}\lib\tcl8.4\thread2.6.3
Source: ..\..\ToInstall\lib\tcl8.4\auto.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\history.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\init.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\ldAout.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\package.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\parray.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\safe.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclConfig-shared.sh; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclConfig.sh; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\tclIndex; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcl8.4\word.tcl; DestDir: {app}\lib\tcl8.4
Source: ..\..\ToInstall\lib\tcllib1.8\aes\aes.tcl; DestDir: {app}\lib\tcllib1.8\aes
Source: ..\..\ToInstall\lib\tcllib1.8\aes\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\aes
Source: ..\..\ToInstall\lib\tcllib1.8\asn\asn.tcl; DestDir: {app}\lib\tcllib1.8\asn
Source: ..\..\ToInstall\lib\tcllib1.8\asn\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\asn
Source: ..\..\ToInstall\lib\tcllib1.8\base64\base64.tcl; DestDir: {app}\lib\tcllib1.8\base64
Source: ..\..\ToInstall\lib\tcllib1.8\base64\base64c.tcl; DestDir: {app}\lib\tcllib1.8\base64
Source: ..\..\ToInstall\lib\tcllib1.8\base64\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\base64
Source: ..\..\ToInstall\lib\tcllib1.8\base64\uuencode.tcl; DestDir: {app}\lib\tcllib1.8\base64
Source: ..\..\ToInstall\lib\tcllib1.8\base64\yencode.tcl; DestDir: {app}\lib\tcllib1.8\base64
Source: ..\..\ToInstall\lib\tcllib1.8\bee\bee.tcl; DestDir: {app}\lib\tcllib1.8\bee
Source: ..\..\ToInstall\lib\tcllib1.8\bee\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\bee
Source: ..\..\ToInstall\lib\tcllib1.8\bench\bench.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bench\bench_read.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bench\bench_wcsv.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bench\bench_wtext.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bench\libbench.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bench\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\bench
Source: ..\..\ToInstall\lib\tcllib1.8\bibtex\bibtex.tcl; DestDir: {app}\lib\tcllib1.8\bibtex
Source: ..\..\ToInstall\lib\tcllib1.8\bibtex\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\bibtex
Source: ..\..\ToInstall\lib\tcllib1.8\blowfish\blowfish.tcl; DestDir: {app}\lib\tcllib1.8\blowfish
Source: ..\..\ToInstall\lib\tcllib1.8\blowfish\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\blowfish
Source: ..\..\ToInstall\lib\tcllib1.8\calendar\calendar.tcl; DestDir: {app}\lib\tcllib1.8\calendar
Source: ..\..\ToInstall\lib\tcllib1.8\calendar\gregorian.tcl; DestDir: {app}\lib\tcllib1.8\calendar
Source: ..\..\ToInstall\lib\tcllib1.8\calendar\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\calendar
Source: ..\..\ToInstall\lib\tcllib1.8\calendar\tclIndex; DestDir: {app}\lib\tcllib1.8\calendar
Source: ..\..\ToInstall\lib\tcllib1.8\cmdline\cmdline.tcl; DestDir: {app}\lib\tcllib1.8\cmdline
Source: ..\..\ToInstall\lib\tcllib1.8\cmdline\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\cmdline
Source: ..\..\ToInstall\lib\tcllib1.8\comm\comm.tcl; DestDir: {app}\lib\tcllib1.8\comm
Source: ..\..\ToInstall\lib\tcllib1.8\comm\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\comm
Source: ..\..\ToInstall\lib\tcllib1.8\control\ascaller.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\assert.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\control.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\do.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\no-op.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\control\tclIndex; DestDir: {app}\lib\tcllib1.8\control
Source: ..\..\ToInstall\lib\tcllib1.8\counter\counter.tcl; DestDir: {app}\lib\tcllib1.8\counter
Source: ..\..\ToInstall\lib\tcllib1.8\counter\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\counter
Source: ..\..\ToInstall\lib\tcllib1.8\crc\cksum.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\crc\crc16.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\crc\crc32.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\crc\crcc.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\crc\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\crc\sum.tcl; DestDir: {app}\lib\tcllib1.8\crc
Source: ..\..\ToInstall\lib\tcllib1.8\csv\csv.tcl; DestDir: {app}\lib\tcllib1.8\csv
Source: ..\..\ToInstall\lib\tcllib1.8\csv\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\csv
Source: ..\..\ToInstall\lib\tcllib1.8\des\des.tcl; DestDir: {app}\lib\tcllib1.8\des
Source: ..\..\ToInstall\lib\tcllib1.8\des\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\des
Source: ..\..\ToInstall\lib\tcllib1.8\des\tcldes.tcl; DestDir: {app}\lib\tcllib1.8\des
Source: ..\..\ToInstall\lib\tcllib1.8\des\tcldesjr.tcl; DestDir: {app}\lib\tcllib1.8\des
Source: ..\..\ToInstall\lib\tcllib1.8\dns\msgs\en.msg; DestDir: {app}\lib\tcllib1.8\dns\msgs
Source: ..\..\ToInstall\lib\tcllib1.8\dns\dns.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\ip.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\ipMore.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\ipMoreC.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\resolv.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\dns\spf.tcl; DestDir: {app}\lib\tcllib1.8\dns
Source: ..\..\ToInstall\lib\tcllib1.8\docstrip\docstrip.tcl; DestDir: {app}\lib\tcllib1.8\docstrip
Source: ..\..\ToInstall\lib\tcllib1.8\docstrip\docstrip_util.tcl; DestDir: {app}\lib\tcllib1.8\docstrip
Source: ..\..\ToInstall\lib\tcllib1.8\docstrip\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\docstrip
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\c.msg; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\de.msg; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\en.msg; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.desc; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.html; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.latex; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.list; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.nroff; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.null; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.text; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.tmml; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fmt.wiki; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\fr.msg; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\idx.html; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\idx.nroff; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\idx.null; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\idx.text; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\idx.wiki; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.html; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.nroff; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.null; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.text; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.tmml; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\toc.wiki; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_common.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_html.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_idx_common.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_nroff.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_text.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_toc_common.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\mpformats\_xml.tcl; DestDir: {app}\lib\tcllib1.8\doctools\mpformats
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\api.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\api_idx.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\api_toc.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\changelog.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\checker.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\checker_idx.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\checker_toc.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\cvs.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\docidx.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\doctoc.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\doctools.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\doctools\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\doctools
Source: ..\..\ToInstall\lib\tcllib1.8\exif\exif.tcl; DestDir: {app}\lib\tcllib1.8\exif
Source: ..\..\ToInstall\lib\tcllib1.8\exif\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\exif
Source: ..\..\ToInstall\lib\tcllib1.8\fileutil\fileutil.tcl; DestDir: {app}\lib\tcllib1.8\fileutil
Source: ..\..\ToInstall\lib\tcllib1.8\fileutil\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\fileutil
Source: ..\..\ToInstall\lib\tcllib1.8\fileutil\traverse.tcl; DestDir: {app}\lib\tcllib1.8\fileutil
Source: ..\..\ToInstall\lib\tcllib1.8\ftp\ftp.tcl; DestDir: {app}\lib\tcllib1.8\ftp
Source: ..\..\ToInstall\lib\tcllib1.8\ftp\ftp_geturl.tcl; DestDir: {app}\lib\tcllib1.8\ftp
Source: ..\..\ToInstall\lib\tcllib1.8\ftp\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ftp
Source: ..\..\ToInstall\lib\tcllib1.8\ftpd\ftpd.tcl; DestDir: {app}\lib\tcllib1.8\ftpd
Source: ..\..\ToInstall\lib\tcllib1.8\ftpd\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ftpd
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\cfront.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\cgen.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\filetypes.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\mimetypes.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\fumagic\rtcore.tcl; DestDir: {app}\lib\tcllib1.8\fumagic
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_fa\dacceptor.tcl; DestDir: {app}\lib\tcllib1.8\grammar_fa
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_fa\dexec.tcl; DestDir: {app}\lib\tcllib1.8\grammar_fa
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_fa\fa.tcl; DestDir: {app}\lib\tcllib1.8\grammar_fa
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_fa\faop.tcl; DestDir: {app}\lib\tcllib1.8\grammar_fa
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_fa\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\grammar_fa
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_me\me_cpu.tcl; DestDir: {app}\lib\tcllib1.8\grammar_me
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_me\me_cpucore.tcl; DestDir: {app}\lib\tcllib1.8\grammar_me
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_me\me_tcl.tcl; DestDir: {app}\lib\tcllib1.8\grammar_me
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_me\me_util.tcl; DestDir: {app}\lib\tcllib1.8\grammar_me
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_me\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\grammar_me
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_peg\peg.tcl; DestDir: {app}\lib\tcllib1.8\grammar_peg
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_peg\peg_interp.tcl; DestDir: {app}\lib\tcllib1.8\grammar_peg
Source: ..\..\ToInstall\lib\tcllib1.8\grammar_peg\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\grammar_peg
Source: ..\..\ToInstall\lib\tcllib1.8\html\html.tcl; DestDir: {app}\lib\tcllib1.8\html
Source: ..\..\ToInstall\lib\tcllib1.8\html\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\html
Source: ..\..\ToInstall\lib\tcllib1.8\htmlparse\htmlparse.tcl; DestDir: {app}\lib\tcllib1.8\htmlparse
Source: ..\..\ToInstall\lib\tcllib1.8\htmlparse\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\htmlparse
Source: ..\..\ToInstall\lib\tcllib1.8\http\autoproxy.tcl; DestDir: {app}\lib\tcllib1.8\http
Source: ..\..\ToInstall\lib\tcllib1.8\http\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\http
Source: ..\..\ToInstall\lib\tcllib1.8\ident\ident.tcl; DestDir: {app}\lib\tcllib1.8\ident
Source: ..\..\ToInstall\lib\tcllib1.8\ident\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ident
Source: ..\..\ToInstall\lib\tcllib1.8\inifile\ini.tcl; DestDir: {app}\lib\tcllib1.8\inifile
Source: ..\..\ToInstall\lib\tcllib1.8\inifile\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\inifile
Source: ..\..\ToInstall\lib\tcllib1.8\irc\irc.tcl; DestDir: {app}\lib\tcllib1.8\irc
Source: ..\..\ToInstall\lib\tcllib1.8\irc\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\irc
Source: ..\..\ToInstall\lib\tcllib1.8\javascript\javascript.tcl; DestDir: {app}\lib\tcllib1.8\javascript
Source: ..\..\ToInstall\lib\tcllib1.8\javascript\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\javascript
Source: ..\..\ToInstall\lib\tcllib1.8\jpeg\jpeg.tcl; DestDir: {app}\lib\tcllib1.8\jpeg
Source: ..\..\ToInstall\lib\tcllib1.8\jpeg\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\jpeg
Source: ..\..\ToInstall\lib\tcllib1.8\ldap\ldap.tcl; DestDir: {app}\lib\tcllib1.8\ldap
Source: ..\..\ToInstall\lib\tcllib1.8\ldap\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ldap
Source: ..\..\ToInstall\lib\tcllib1.8\log\msgs\en.msg; DestDir: {app}\lib\tcllib1.8\log\msgs
Source: ..\..\ToInstall\lib\tcllib1.8\log\log.tcl; DestDir: {app}\lib\tcllib1.8\log
Source: ..\..\ToInstall\lib\tcllib1.8\log\logger.tcl; DestDir: {app}\lib\tcllib1.8\log
Source: ..\..\ToInstall\lib\tcllib1.8\log\loggerAppender.tcl; DestDir: {app}\lib\tcllib1.8\log
Source: ..\..\ToInstall\lib\tcllib1.8\log\loggerUtils.tcl; DestDir: {app}\lib\tcllib1.8\log
Source: ..\..\ToInstall\lib\tcllib1.8\log\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\log
Source: ..\..\ToInstall\lib\tcllib1.8\math\bessel.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bigfloat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bigfloat2.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\bignum.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\calculus.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\classic_polyns.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\combinatorics.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\constants.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\elliptic.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\exponential.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\fourier.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\fuzzy.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\geometry.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\interpolate.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\linalg.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\liststat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\math.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\misc.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\optimize.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\pdf_stat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\plotstat.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\polynomials.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\qcomplex.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\rational_funcs.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\romannumerals.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\special.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\statistics.tcl; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\math\tclIndex; DestDir: {app}\lib\tcllib1.8\math
Source: ..\..\ToInstall\lib\tcllib1.8\md4\md4.tcl; DestDir: {app}\lib\tcllib1.8\md4
Source: ..\..\ToInstall\lib\tcllib1.8\md4\md4c.tcl; DestDir: {app}\lib\tcllib1.8\md4
Source: ..\..\ToInstall\lib\tcllib1.8\md4\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\md4
Source: ..\..\ToInstall\lib\tcllib1.8\md5\md5.tcl; DestDir: {app}\lib\tcllib1.8\md5
Source: ..\..\ToInstall\lib\tcllib1.8\md5\md5c.tcl; DestDir: {app}\lib\tcllib1.8\md5
Source: ..\..\ToInstall\lib\tcllib1.8\md5\md5x.tcl; DestDir: {app}\lib\tcllib1.8\md5
Source: ..\..\ToInstall\lib\tcllib1.8\md5\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\md5
Source: ..\..\ToInstall\lib\tcllib1.8\md5crypt\md5crypt.tcl; DestDir: {app}\lib\tcllib1.8\md5crypt
Source: ..\..\ToInstall\lib\tcllib1.8\md5crypt\md5cryptc.tcl; DestDir: {app}\lib\tcllib1.8\md5crypt
Source: ..\..\ToInstall\lib\tcllib1.8\md5crypt\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\md5crypt
Source: ..\..\ToInstall\lib\tcllib1.8\mime\mime.tcl; DestDir: {app}\lib\tcllib1.8\mime
Source: ..\..\ToInstall\lib\tcllib1.8\mime\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\mime
Source: ..\..\ToInstall\lib\tcllib1.8\mime\smtp.tcl; DestDir: {app}\lib\tcllib1.8\mime
Source: ..\..\ToInstall\lib\tcllib1.8\multiplexer\multiplexer.tcl; DestDir: {app}\lib\tcllib1.8\multiplexer
Source: ..\..\ToInstall\lib\tcllib1.8\multiplexer\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\multiplexer
Source: ..\..\ToInstall\lib\tcllib1.8\ncgi\ncgi.tcl; DestDir: {app}\lib\tcllib1.8\ncgi
Source: ..\..\ToInstall\lib\tcllib1.8\ncgi\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ncgi
Source: ..\..\ToInstall\lib\tcllib1.8\nntp\nntp.tcl; DestDir: {app}\lib\tcllib1.8\nntp
Source: ..\..\ToInstall\lib\tcllib1.8\nntp\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\nntp
Source: ..\..\ToInstall\lib\tcllib1.8\ntp\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ntp
Source: ..\..\ToInstall\lib\tcllib1.8\ntp\time.tcl; DestDir: {app}\lib\tcllib1.8\ntp
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\config_peg.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\reader_hb.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\reader_lemon.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\reader_peg.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\reader_ser.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\reader_treeser.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\transform_reachable.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\transform_realizable.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_hb.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_identity.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_me.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_null.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_peg.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_ser.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_tpc.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\plugins\writer_tree.tcl; DestDir: {app}\lib\tcllib1.8\page\plugins
Source: ..\..\ToInstall\lib\tcllib1.8\page\analysis_peg_emodes.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\analysis_peg_minimize.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\analysis_peg_reachable.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\analysis_peg_realizable.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_peg_canon.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_peg_cpkg.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_peg_hb.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_peg_me.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_peg_ser.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\gen_tree_text.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\parse_lemon.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\parse_peg.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\parse_peghb.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\parse_pegser.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\peg_grammar.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\pluginmgr.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\util_flow.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\util_norm_lemon.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\util_norm_peg.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\util_peg.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\page\util_quote.tcl; DestDir: {app}\lib\tcllib1.8\page
Source: ..\..\ToInstall\lib\tcllib1.8\pluginmgr\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\pluginmgr
Source: ..\..\ToInstall\lib\tcllib1.8\pluginmgr\pluginmgr.tcl; DestDir: {app}\lib\tcllib1.8\pluginmgr
Source: ..\..\ToInstall\lib\tcllib1.8\png\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\png
Source: ..\..\ToInstall\lib\tcllib1.8\png\png.tcl; DestDir: {app}\lib\tcllib1.8\png
Source: ..\..\ToInstall\lib\tcllib1.8\pop3\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\pop3
Source: ..\..\ToInstall\lib\tcllib1.8\pop3\pop3.tcl; DestDir: {app}\lib\tcllib1.8\pop3
Source: ..\..\ToInstall\lib\tcllib1.8\pop3d\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\pop3d
Source: ..\..\ToInstall\lib\tcllib1.8\pop3d\pop3d.tcl; DestDir: {app}\lib\tcllib1.8\pop3d
Source: ..\..\ToInstall\lib\tcllib1.8\pop3d\pop3d_dbox.tcl; DestDir: {app}\lib\tcllib1.8\pop3d
Source: ..\..\ToInstall\lib\tcllib1.8\pop3d\pop3d_udb.tcl; DestDir: {app}\lib\tcllib1.8\pop3d
Source: ..\..\ToInstall\lib\tcllib1.8\profiler\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\profiler
Source: ..\..\ToInstall\lib\tcllib1.8\profiler\profiler.tcl; DestDir: {app}\lib\tcllib1.8\profiler
Source: ..\..\ToInstall\lib\tcllib1.8\rc4\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\rc4
Source: ..\..\ToInstall\lib\tcllib1.8\rc4\rc4.tcl; DestDir: {app}\lib\tcllib1.8\rc4
Source: ..\..\ToInstall\lib\tcllib1.8\rc4\rc4c.tcl; DestDir: {app}\lib\tcllib1.8\rc4
Source: ..\..\ToInstall\lib\tcllib1.8\rcs\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\rcs
Source: ..\..\ToInstall\lib\tcllib1.8\rcs\rcs.tcl; DestDir: {app}\lib\tcllib1.8\rcs
Source: ..\..\ToInstall\lib\tcllib1.8\report\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\report
Source: ..\..\ToInstall\lib\tcllib1.8\report\report.tcl; DestDir: {app}\lib\tcllib1.8\report
Source: ..\..\ToInstall\lib\tcllib1.8\ripemd\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\ripemd
Source: ..\..\ToInstall\lib\tcllib1.8\ripemd\ripemd128.tcl; DestDir: {app}\lib\tcllib1.8\ripemd
Source: ..\..\ToInstall\lib\tcllib1.8\ripemd\ripemd160.tcl; DestDir: {app}\lib\tcllib1.8\ripemd
Source: ..\..\ToInstall\lib\tcllib1.8\sasl\ntlm.tcl; DestDir: {app}\lib\tcllib1.8\sasl
Source: ..\..\ToInstall\lib\tcllib1.8\sasl\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\sasl
Source: ..\..\ToInstall\lib\tcllib1.8\sasl\sasl.tcl; DestDir: {app}\lib\tcllib1.8\sasl
Source: ..\..\ToInstall\lib\tcllib1.8\sha1\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\sha1
Source: ..\..\ToInstall\lib\tcllib1.8\sha1\sha1.tcl; DestDir: {app}\lib\tcllib1.8\sha1
Source: ..\..\ToInstall\lib\tcllib1.8\sha1\sha1c.tcl; DestDir: {app}\lib\tcllib1.8\sha1
Source: ..\..\ToInstall\lib\tcllib1.8\sha1\sha1v1.tcl; DestDir: {app}\lib\tcllib1.8\sha1
Source: ..\..\ToInstall\lib\tcllib1.8\sha1\sha256.tcl; DestDir: {app}\lib\tcllib1.8\sha1
Source: ..\..\ToInstall\lib\tcllib1.8\smtpd\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\smtpd
Source: ..\..\ToInstall\lib\tcllib1.8\smtpd\smtpd.tcl; DestDir: {app}\lib\tcllib1.8\smtpd
Source: ..\..\ToInstall\lib\tcllib1.8\snit\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\snit\snit.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\snit\snit2.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\snit\snit83.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\snit\snit84.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\snit\snit_tcl83_utils.tcl; DestDir: {app}\lib\tcllib1.8\snit
Source: ..\..\ToInstall\lib\tcllib1.8\soundex\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\soundex
Source: ..\..\ToInstall\lib\tcllib1.8\soundex\soundex.tcl; DestDir: {app}\lib\tcllib1.8\soundex
Source: ..\..\ToInstall\lib\tcllib1.8\stooop\mkpkgidx.tcl; DestDir: {app}\lib\tcllib1.8\stooop
Source: ..\..\ToInstall\lib\tcllib1.8\stooop\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\stooop
Source: ..\..\ToInstall\lib\tcllib1.8\stooop\stooop.tcl; DestDir: {app}\lib\tcllib1.8\stooop
Source: ..\..\ToInstall\lib\tcllib1.8\stooop\switched.tcl; DestDir: {app}\lib\tcllib1.8\stooop
Source: ..\..\ToInstall\lib\tcllib1.8\stooop\xifo.tcl; DestDir: {app}\lib\tcllib1.8\stooop
Source: ..\..\ToInstall\lib\tcllib1.8\struct\graph.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\graph1.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\list.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\matrix.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\matrix1.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\pool.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\prioqueue.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\queue.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\record.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\sets.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\skiplist.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\stack.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\struct.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\struct1.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\tree.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\tree1.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\tree_c.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\struct\tree_tcl.tcl; DestDir: {app}\lib\tcllib1.8\struct
Source: ..\..\ToInstall\lib\tcllib1.8\tar\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\tar
Source: ..\..\ToInstall\lib\tcllib1.8\tar\tar.tcl; DestDir: {app}\lib\tcllib1.8\tar
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\adjust.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\dehypht.tex; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\eshyph_vo.tex; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\expander.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\ithyph.tex; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\split.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\tabify.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\textutil.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\textutil\trim.tcl; DestDir: {app}\lib\tcllib1.8\textutil
Source: ..\..\ToInstall\lib\tcllib1.8\tie\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_array.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_dsource.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_file.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_growfile.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_log.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\tie\tie_rarray.tcl; DestDir: {app}\lib\tcllib1.8\tie
Source: ..\..\ToInstall\lib\tcllib1.8\treeql\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\treeql
Source: ..\..\ToInstall\lib\tcllib1.8\treeql\treeql.tcl; DestDir: {app}\lib\tcllib1.8\treeql
Source: ..\..\ToInstall\lib\tcllib1.8\treeql\treeql84.tcl; DestDir: {app}\lib\tcllib1.8\treeql
Source: ..\..\ToInstall\lib\tcllib1.8\treeql\treeql85.tcl; DestDir: {app}\lib\tcllib1.8\treeql
Source: ..\..\ToInstall\lib\tcllib1.8\units\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\units
Source: ..\..\ToInstall\lib\tcllib1.8\units\units.tcl; DestDir: {app}\lib\tcllib1.8\units
Source: ..\..\ToInstall\lib\tcllib1.8\uri\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\uri
Source: ..\..\ToInstall\lib\tcllib1.8\uri\uri.tcl; DestDir: {app}\lib\tcllib1.8\uri
Source: ..\..\ToInstall\lib\tcllib1.8\uri\urn-scheme.tcl; DestDir: {app}\lib\tcllib1.8\uri
Source: ..\..\ToInstall\lib\tcllib1.8\uuid\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8\uuid
Source: ..\..\ToInstall\lib\tcllib1.8\uuid\uuid.tcl; DestDir: {app}\lib\tcllib1.8\uuid
Source: ..\..\ToInstall\lib\tcllib1.8\pkgIndex.tcl; DestDir: {app}\lib\tcllib1.8
Source: ..\..\ToInstall\lib\tcllib1.8\tcllib.tap; DestDir: {app}\lib\tcllib1.8
Source: ..\..\ToInstall\lib\tk8.4\demos\images\earth.gif; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\earthris.gif; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\face.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\flagdown.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\flagup.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\gray25.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\letters.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\noletter.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\pattern.bmp; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\tcllogo.gif; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\images\teapot.ppm; DestDir: {app}\lib\tk8.4\demos\images
Source: ..\..\ToInstall\lib\tk8.4\demos\arrow.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\bind.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\bitmap.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\browse; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\button.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\check.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\clrpick.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\colors.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\cscroll.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\ctext.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\dialog1.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\dialog2.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\entry1.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\entry2.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\entry3.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\filebox.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\floor.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\form.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\hello; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\hscale.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\icon.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\image1.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\image2.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\items.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\ixset; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\label.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\labelframe.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\menu.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\menubu.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\msgbox.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\paned1.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\paned2.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\plot.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\puzzle.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\radio.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\README; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\rmt; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\rolodex; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\ruler.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\sayings.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\search.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\spin.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\square; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\states.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\style.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\tclIndex; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\tcolor; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\text.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\timer; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\twind.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\unicodeout.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\vscale.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\demos\widget.tcl; DestDir: {app}\lib\tk8.4\demos
Source: ..\..\ToInstall\lib\tk8.4\images\logo.eps; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\logo100.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\logo64.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\logoLarge.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\logoMed.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo.eps; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo100.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo150.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo175.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo200.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\pwrdLogo75.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\README; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\images\tai-ku.gif; DestDir: {app}\lib\tk8.4\images
Source: ..\..\ToInstall\lib\tk8.4\msgs\cs.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\de.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\el.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\en.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\en_gb.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\eo.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\es.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\es_ES.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\fr.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\it.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\nl.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\pl.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\pt.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\msgs\ru.msg; DestDir: {app}\lib\tk8.4\msgs
Source: ..\..\ToInstall\lib\tk8.4\bgerror.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\button.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\choosedir.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\clrpick.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\comdlg.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\console.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\dialog.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\entry.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\focus.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\listbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\menu.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\mkpsenc.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\msgbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\obsolete.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\optMenu.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\palette.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\panedwindow.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\pkgIndex.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\prolog.ps; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\safetk.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\scale.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\scrlbar.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\spinbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tclIndex; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tearoff.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\text.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tk.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkAppInit.c; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkConfig-shared.sh; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkConfig.sh; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\tkfbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\unsupported.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\tk8.4\xmfbox.tcl; DestDir: {app}\lib\tk8.4
Source: ..\..\ToInstall\lib\twapi\doc\readme.txt; DestDir: {app}\lib\twapi\doc
Source: ..\..\ToInstall\lib\twapi\doc\twapi.chm; DestDir: {app}\lib\twapi\doc
Source: ..\..\ToInstall\lib\twapi\tests\all.tcl; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\clipboard.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\com.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\console.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\disk.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\disk.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\eventlog.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\network.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\nls.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\osinfo.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\osinfo.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\parseargs.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\process.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\process.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\security.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\services.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\services.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\share.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\share.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\shell.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\testutil.tcl; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\thread.vbs; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\try.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\tests\ui.test; DestDir: {app}\lib\twapi\tests
Source: ..\..\ToInstall\lib\twapi\clipboard.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\com.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\console.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\desktop.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\disk.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\eventlog.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\LICENSE; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\network.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\nls.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\osinfo.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\pdh.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\pkgIndex.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\printer.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\process.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\security.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\services.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\share.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\shell.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\synch.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapi.dll; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapi.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\twapicallback.dll; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\twapi\ui.tcl; DestDir: {app}\lib\twapi
Source: ..\..\ToInstall\lib\vtk\vtkcommon\vtkcommon.tcl; DestDir: {app}\lib\vtk\vtkcommon
Source: ..\..\ToInstall\lib\vtk\vtkfiltering\vtkfiltering.tcl; DestDir: {app}\lib\vtk\vtkfiltering
Source: ..\..\ToInstall\lib\vtk\vtkgraphics\vtkgraphics.tcl; DestDir: {app}\lib\vtk\vtkgraphics
Source: ..\..\ToInstall\lib\vtk\vtkhybrid\vtkhybrid.tcl; DestDir: {app}\lib\vtk\vtkhybrid
Source: ..\..\ToInstall\lib\vtk\vtkimaging\vtkimaging.tcl; DestDir: {app}\lib\vtk\vtkimaging
Source: ..\..\ToInstall\lib\vtk\vtkio\vtkio.tcl; DestDir: {app}\lib\vtk\vtkio
Source: ..\..\ToInstall\lib\vtk\vtkrendering\vtkrendering.tcl; DestDir: {app}\lib\vtk\vtkrendering
Source: ..\..\ToInstall\lib\vtk\vtkvolumerendering\vtkvolumerendering.tcl; DestDir: {app}\lib\vtk\vtkvolumerendering
Source: ..\..\ToInstall\lib\vtk\vtkwidgets\vtkwidgets.tcl; DestDir: {app}\lib\vtk\vtkwidgets
Source: ..\..\ToInstall\lib\vtk\bindings-iw.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\bindings-rw.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\bindings.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\Interactor.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\pkgIndex.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\setget.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtk.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkbase.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkCommon.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkCommonTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkDICOMParser.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkexoIIc.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkexpat.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkFiltering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkFilteringTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkfreetype.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkftgl.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGenericFiltering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGenericFilteringTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGraphics.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkGraphicsTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkHybrid.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkHybridTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkImaging.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkImagingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkinteraction.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkIO.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkIOTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkjpeg.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkMPEG2Encode.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkNetCDF.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkParallel.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkParallelTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkpng.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkRendering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkRenderingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtksys.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtktesting.tcl; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtktiff.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkVolumeRendering.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkVolumeRenderingTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkWidgets.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkWidgetsTCL.dll; DestDir: {app}\lib\vtk
Source: ..\..\ToInstall\lib\vtk\vtkzlib.dll; DestDir: {app}\lib\vtk

[Icons]
Name: {group}\Brandy Mol; Filename: {app}\bin\launcher.exe; IconIndex: 0; Tasks: ; Languages: ; WorkingDir: {app}\bin; IconFilename: {app}\bin\brandy.ico
Name: {group}\{cm:UninstallProgram,Brandy Mol}; Filename: {uninstallexe}; IconFilename: {app}\bin\brandy.ico; IconIndex: 0
Name: {commondesktop}\Brandy Mol; Filename: {app}\bin\launcher.exe; Tasks: desktopicon; IconIndex: 0; WorkingDir: {app}\bin; IconFilename: {app}\bin\brandy.ico
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\Brandy Mol; Filename: {app}\bin\launcher.exe; Tasks: quicklaunchicon; IconIndex: 0; WorkingDir: {app}\bin; Languages: ; IconFilename: {app}\bin\brandy.ico

[Run]
Filename: {tmp}\unzip.bat; WorkingDir: {tmp}; Parameters: {app}\bin; Description: unzip; Flags: shellexec runhidden

Filename: {tmp}\draw25.exe; Description: Instalar MDL Isis Draw 2.5; Flags: postinstall skipifdoesntexist
Filename: {tmp}\MDLChime26SP4.exe; Description: Instalar MDL Chime; Flags: postinstall skipifdoesntexist
Filename: {tmp}\help25.exe; Description: Instalar Ayudas de Isis Draw; Flags: postinstall skipifdoesntexist
Filename: {tmp}\AN2000.exe; Description: Instalar Modulo de Nomenclatura para Isis Draw; Flags: postinstall skipifdoesntexist
Filename: {app}\bin\launcher.exe; Description: {cm:LaunchProgram,Brandy Mol}; Flags: nowait postinstall skipifsilent unchecked; WorkingDir: {app}\bin




[Dirs]
Name: {app}\bin
Name: {app}\chm
Name: {app}\lib
Name: {app}\twapi
Name: {app}\twapi
Name: {app}\lib

[INI]
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_PPAL>; String: {app}\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_CHM>; String: {app}\chm\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_TEMP>; String: {app}\temp\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_BIN>; String: {app}\bin\; Tasks: ; Languages: 
Filename: {app}\bin\conf.ini; Section: Directorios; Key: <DIR_DATA>; String: {app}\data\
Filename: {app}\bin\conf.ini; Section: Preferencias; Key: <escala>; String: 9.1
Filename: {app}\bin\conf.ini; Section: Preferencias; Key: <CONSOLE>; String: hide
Filename: {app}\bin\conf.ini; Section: Preferencias; Key: <LENGUAJE>; String: lang_ES.lang

[Registry]
Root: HKLM; Subkey: SOFTWARE\Brandy Mol; ValueType: string; ValueName: Path; ValueData: {app}; Tasks: ; Languages: 
[LangOptions]
LanguageName=English
LanguageID=$0409

[_ISToolDownload]
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/analyze.zip; DestDir: {tmp}; DestName: analyze.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/minimize.zip; DestDir: {tmp}; DestName: minimize.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/newton.zip; DestDir: {tmp}; DestName: newton.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/optimize.zip; DestDir: {tmp}; DestName: optimize.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/path.zip; DestDir: {tmp}; DestName: path.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/saddle.zip; DestDir: {tmp}; DestName: saddle.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/scan.zip; DestDir: {tmp}; DestName: scan.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/spacefill.zip; DestDir: {tmp}; DestName: spacefill.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/superpose.zip; DestDir: {tmp}; DestName: superpose.zip
Source: ftp://dasher.wustl.edu/pub/tinker-bin/windows/vibrate.zip; DestDir: {tmp}; DestName: vibrate.zip
[Code]
// Function generated by ISTool.
function NextButtonClick(CurPage: Integer): Boolean;
begin
	Result := istool_download(CurPage);
end;
